# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/pyosangwoo/Documents/GitHub/OOAD_Project/manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManagerWindow(object):
    def setupUi(self, ManagerWindow):
        ManagerWindow.setObjectName("ManagerWindow")
        ManagerWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ManagerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainmenu = QtWidgets.QPushButton(self.centralwidget)
        self.mainmenu.setGeometry(QtCore.QRect(670, 20, 113, 32))
        self.mainmenu.setObjectName("mainmenu")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 140, 151, 61))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(130, 80, 121, 31))
        self.textEdit.setObjectName("textEdit")
        self.FixedParkingList = QtWidgets.QListView(self.centralwidget)
        self.FixedParkingList.setGeometry(QtCore.QRect(30, 230, 741, 311))
        self.FixedParkingList.setObjectName("FixedParkingList")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 140, 151, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 90, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 311, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 140, 151, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        ManagerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ManagerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        ManagerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ManagerWindow)
        self.statusbar.setObjectName("statusbar")
        ManagerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ManagerWindow)
        QtCore.QMetaObject.connectSlotsByName(ManagerWindow)

    def retranslateUi(self, ManagerWindow):
        _translate = QtCore.QCoreApplication.translate
        ManagerWindow.setWindowTitle(_translate("ManagerWindow", "ManagerWindow"))
        self.mainmenu.setText(_translate("ManagerWindow", "메인 메뉴"))
        self.pushButton.setText(_translate("ManagerWindow", "고정 주차 차량 삭제"))
        self.textEdit.setHtml(_translate("ManagerWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("ManagerWindow", "고정 주차 차량 등록"))
        self.label.setText(_translate("ManagerWindow", "차량 번호"))
        self.label_2.setText(_translate("ManagerWindow", "차량 번호를 입력하고 고정 주차를 등록, 삭제 하세요"))
        self.pushButton_3.setText(_translate("ManagerWindow", "고정 주차 차량 확인"))
