# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/pyosangwoo/Documents/GitHub/OOAD_Project/manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManagerWindow(object):
    def setupUi(self, ManagerWindow):
        ManagerWindow.setObjectName("ManagerWindow")
        ManagerWindow.setEnabled(True)
        ManagerWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ManagerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainmenu = QtWidgets.QPushButton(self.centralwidget)
        self.mainmenu.setGeometry(QtCore.QRect(660, 20, 113, 32))
        self.mainmenu.setObjectName("mainmenu")
        self.FixedCarList = QtWidgets.QTableWidget(self.centralwidget)
        self.FixedCarList.setGeometry(QtCore.QRect(60, 180, 311, 241))
        self.FixedCarList.setObjectName("FixedCarList")
        self.FixedCarList.setColumnCount(2)
        self.FixedCarList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.FixedCarList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.FixedCarList.setHorizontalHeaderItem(1, item)
        self.addbtn = QtWidgets.QPushButton(self.centralwidget)
        self.addbtn.setGeometry(QtCore.QRect(430, 350, 141, 51))
        self.addbtn.setObjectName("addbtn")
        self.fixedcarnum = QtWidgets.QTextEdit(self.centralwidget)
        self.fixedcarnum.setGeometry(QtCore.QRect(570, 220, 121, 31))
        self.fixedcarnum.setObjectName("fixedcarnum")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(470, 230, 61, 16))
        self.label_2.setObjectName("label_2")
        self.fixedcarlotnum = QtWidgets.QTextEdit(self.centralwidget)
        self.fixedcarlotnum.setGeometry(QtCore.QRect(570, 280, 121, 31))
        self.fixedcarlotnum.setObjectName("fixedcarlotnum")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 290, 91, 16))
        self.label_3.setObjectName("label_3")
        self.delbtn = QtWidgets.QPushButton(self.centralwidget)
        self.delbtn.setGeometry(QtCore.QRect(590, 350, 141, 51))
        self.delbtn.setObjectName("delbtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 150, 121, 16))
        self.label.setObjectName("label")
        ManagerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ManagerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        ManagerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ManagerWindow)
        self.statusbar.setObjectName("statusbar")
        ManagerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ManagerWindow)
        QtCore.QMetaObject.connectSlotsByName(ManagerWindow)

    def retranslateUi(self, ManagerWindow):
        _translate = QtCore.QCoreApplication.translate
        ManagerWindow.setWindowTitle(_translate("ManagerWindow", "ManagerWindow"))
        self.mainmenu.setText(_translate("ManagerWindow", "메인 메뉴"))
        item = self.FixedCarList.horizontalHeaderItem(0)
        item.setText(_translate("ManagerWindow", "차량 번호"))
        item = self.FixedCarList.horizontalHeaderItem(1)
        item.setText(_translate("ManagerWindow", "주차장 위치 번호"))
        self.addbtn.setText(_translate("ManagerWindow", "고정 주차 차량 등록"))
        self.label_2.setText(_translate("ManagerWindow", "차량 번호"))
        self.label_3.setText(_translate("ManagerWindow", "주차 위치 번호"))
        self.delbtn.setText(_translate("ManagerWindow", "고정 주차 차량 삭제"))
        self.label.setText(_translate("ManagerWindow", "고정 주차 차량 목록"))
